"""Tests for the AppArmor profile generator."""

import sys
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).parent.parent))

from linuxaudit.apparmor_gen import (
    _detect_category,
    _profile_name_from_path,
    _resolve_binary,
    build_apparmor_profile,
    generate_profile,
)


# ── _profile_name_from_path ──────────────────────────────────────────────────

def test_profile_name_simple():
    assert _profile_name_from_path("/usr/bin/nginx") == "usr.bin.nginx"

def test_profile_name_sbin():
    assert _profile_name_from_path("/usr/sbin/sshd") == "usr.sbin.sshd"

def test_profile_name_no_leading_slash():
    assert _profile_name_from_path("usr/bin/curl") == "usr.bin.curl"


# ── _detect_category ─────────────────────────────────────────────────────────

def test_category_web_server():
    assert _detect_category("/usr/sbin/nginx", []) == "web_server"
    assert _detect_category("/usr/sbin/apache2", []) == "web_server"

def test_category_ssh():
    assert _detect_category("/usr/sbin/sshd", []) == "ssh_server"

def test_category_interpreter():
    assert _detect_category("/usr/bin/python3", []) == "interpreter"
    assert _detect_category("/usr/bin/ruby", []) == "interpreter"

def test_category_shell():
    assert _detect_category("/bin/bash", []) == "shell"
    assert _detect_category("/bin/zsh", []) == "shell"

def test_category_network_tool():
    assert _detect_category("/usr/bin/curl", []) == "network_tool"
    assert _detect_category("/usr/bin/wget", []) == "network_tool"

def test_category_tls_via_libs():
    libs = ["/lib/x86_64-linux-gnu/libssl.so.3"]
    assert _detect_category("/usr/bin/sometool", libs) == "tls_app"

def test_category_generic_fallback():
    assert _detect_category("/usr/bin/unknowntool", []) == "generic"


# ── generate_profile ─────────────────────────────────────────────────────────

def test_profile_contains_binary():
    profile = generate_profile("/usr/bin/curl", [], "network_tool", False)
    assert "/usr/bin/curl" in profile

def test_profile_has_deny_shadow():
    profile = generate_profile("/usr/bin/curl", [], "network_tool", False)
    assert "deny /etc/shadow" in profile

def test_profile_has_deny_ptrace():
    profile = generate_profile("/usr/bin/curl", [], "generic", False)
    assert "deny ptrace" in profile

def test_profile_web_server_rules():
    profile = generate_profile("/usr/sbin/nginx", [], "web_server", False)
    assert "/var/www/**" in profile
    assert "network inet  stream" in profile

def test_profile_ssh_server_rules():
    profile = generate_profile("/usr/sbin/sshd", [], "ssh_server", False)
    assert "/etc/ssh/**" in profile
    assert "authorized_keys" in profile

def test_profile_has_header_comment():
    profile = generate_profile("/usr/bin/python3", [], "interpreter", True)
    assert "Generated by linuxaudit" in profile
    assert "REVIEW BEFORE LOADING" in profile

def test_profile_lib_dirs_included():
    libs = ["/lib/x86_64-linux-gnu/libssl.so.3", "/lib/x86_64-linux-gnu/libc.so.6"]
    profile = generate_profile("/usr/bin/curl", libs, "network_tool", False)
    assert "/lib/x86_64-linux-gnu/" in profile

def test_profile_flags_attach_disconnected():
    profile = generate_profile("/usr/bin/curl", [], "generic", False)
    assert "flags=(attach_disconnected)" in profile


# ── build_apparmor_profile ────────────────────────────────────────────────────

def test_build_with_invalid_binary(tmp_path):
    result = build_apparmor_profile("/nonexistent/binary/xyz")
    assert result["status"] == "FAIL"
    assert "nonexistent" in result["message"]
    assert result["profile"] is None

def test_build_with_valid_binary(tmp_path):
    out = str(tmp_path / "test.apparmor")
    result = build_apparmor_profile("/bin/sh", output_path=out)
    assert result["status"] == "PASS"
    assert result["binary"] == "/bin/sh"
    assert result["profile"] is not None
    assert Path(out).exists()
    content = Path(out).read_text()
    assert "/bin/sh" in content

def test_build_writes_file(tmp_path):
    out = str(tmp_path / "nginx.apparmor")
    with mock.patch("linuxaudit.apparmor_gen._resolve_binary", return_value="/usr/sbin/nginx"):
        with mock.patch("linuxaudit.apparmor_gen._get_linked_libs", return_value=[]):
            with mock.patch("linuxaudit.apparmor_gen._is_running", return_value=False):
                result = build_apparmor_profile("nginx", output_path=out)
    assert result["status"] == "PASS"
    assert Path(out).exists()

def test_build_result_schema(tmp_path):
    out = str(tmp_path / "sh.apparmor")
    result = build_apparmor_profile("/bin/sh", output_path=out)
    required = {"name", "status", "severity", "message", "recommendation",
                "profile", "output_path", "binary", "category", "linked_libs", "is_running"}
    assert required.issubset(set(result.keys()))
